name: flutter_todos
description: todo app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.1
  flutter_native_splash: ^2.1.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  
  
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  local_storage_todos_api:
    path: packages/local_storage_todos_api
  todos_api:
    path: packages/todos_api
  todos_repository:
    path: packages/todos_repository

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_test:
    sdk: flutter
  mockingjay: ^0.2.0
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/splash_image.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash_image.png